version: "3.9"

services:
  lingobox:
    image: ghcr.io/huyenph/lingobox/lingobox:latest
    container_name: lingobox
    restart: always
    env_file:
      - .env
    environment:
      - APP_ENV=production
    networks:
      - appnet

networks:
  appnet:
    external: true
